---

# mdatp = Microsoft Defender Advanced Threat Protection

mdatp_root: /etc/opt/microsoft/mdatp

mdatp_onboard_json_dest: "{{ mdatp_root }}/mdatp_onboard.json"
mdatp_managed_json_dest: "{{ mdatp_root }}/managed/mdatp_managed.json"

# This will likely be the key for the 26.04 repo
#mdatp_apt_key_url: https://packages.microsoft.com/keys/microsoft-2025.asc
#mdatp_apt_key_checksum: "sha256:d45224d594d969f084232deaaf97c58ca502a9d964c362d7aaef5a76e16b3dd1"
mdatp_apt_key_url: https://packages.microsoft.com/keys/microsoft.asc
mdatp_apt_key_checksum: "sha256:2fa9c05d591a1582a9aba276272478c262e95ad00acf60eaee1644d93941e3c6"

mdatp_apt_repo_distro: "{{ ansible_distribution|lower }}"
mdatp_apt_repo_version: "{{ ansible_distribution_version }}"
mdatp_apt_repo_channel: "{{ ansible_distribution_release }}"
mdatp_apt_repo_url: "https://packages.microsoft.com/{{ mdatp_apt_repo_distro }}/{{ mdatp_apt_repo_version }}/prod"

mdatp_packages:
  - mdatp
