---

- name: Pulsar Servers
  hosts: pulsar_servers
  roles:
    - role: galaxyproject.general.paths
    - role: galaxyproject.general.copy
    - role: galaxyproject.miniconda
    - role: galaxyproject.pulsar
      tags: pulsar
    - role: galaxyproject.cvmfsexec
      when: "'hpc_pulsar_servers' in group_names"
    - role: usegalaxy_org.hpc_pulsar_servers
      when: "'hpc_pulsar_servers' in group_names"
