---

jenkinsservers_group_authorized_key_users: "{{ vault_jenkinsservers_group_authorized_key_users }}"
jenkinsservers_group_private_key_users: "{{ vault_jenkinsservers_group_private_key_users }}"

jenkinsservers_group_apt_keys:
  - url: 'http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key'

jenkinsservers_group_apt_repositories:
  - repo: 'deb http://http.debian.net/debian jessie-backports main contrib non-free'
  - repo: 'deb http://pkg.jenkins-ci.org/debian binary/'

jenkinsservers_group_packages:
  - git
  - postgresql-9.4
  - python-virtualenv
  - jenkins
  - npm
  - nodejs-legacy
  # TS packages
  - autoconf
  - automake
  - build-essential
  - gfortran
  - cmake
  - git-core
  - libatlas-base-dev
  - libblas-dev
  - liblapack-dev
  - openssl
  - python-dev
  - python-setuptools
  - python-virtualenv
  - zlib1g-dev
  - libyaml-dev
  - subversion
  - python-dev
  - pkg-config
  - unzip
  - docker.io
  - samtools
  - sudo
  - curl
  - ntp
  - ntpdate
  # for jenkins, is this right or is it using 8 now?
  - openjdk-7-jre-headless

jenkinsservers_group_users:
  - name: jenkins
    groups: docker

group_crontabs:
  - id: jenkins_backup
    name: Jenkins Backup
    user: jenkins
    hour: 22
    minute: 0
    job: rsync -av --delete --exclude='jobs/*/workspace*' --exclude='.cache' /var/lib/jenkins/ zfsdump-leeroy@westvleteren.galaxyproject.org:/zones/westvleteren/backup/leeroy/jenkins && ssh -T zfsdump-leeroy@westvleteren.galaxyproject.org -- /usr/sbin/zfs snapshot zones/westvleteren/backup/leeroy/jenkins@`date -u +\%Y\%m\%dT\%H\%M\%SZ`

# TODO: generate this file automatically from structured data
# Maybe this? https://github.com/gaqzi/ansible-ssh-config
jenkinsservers_group_files:
  - src: files/jenkins/jenkins_server_user_ssh_config
    dest: ~jenkins/.ssh/config
    owner: jenkins
    group: jenkins

linuxbrew_user_name: jenkins
linuxbrew_user_home: /var/lib/jenkins
linuxbrew_user_shellrc: "{{ linuxbrew_user_home }}/.bashrc"

linuxbrew_taps:
  - homebrew/science
  - galaxyproject/tap
linuxbrew_recipes:
  - bcftools
  - planemo
  - node
