---

host_authorized_key_users: "{{ vault_host_authorized_key_users }}"
cvmfs_private_keys: "{{ vault_cvmfs_private_keys }}"

cvmfs_manage_firewall: true
galaxy_cvmfs_repos_enabled: false
cvmfs_repositories:
  - repository: data.galaxyproject.org
    stratum0: cvmfs0-psu0.galaxyproject.org
    owner: g2test
    server_options:
      - CVMFS_AUTO_TAG=false
      - CVMFS_GARBAGE_COLLECTION=true
      - CVMFS_AUTO_GC=false
      - CVMFS_IGNORE_XDIR_HARDLINKS=false
    client_options: []
  - repository: sandbox.galaxyproject.org
    stratum0: cvmfs0-psu0.galaxyproject.org
    owner: sandbox
    server_options:
      - CVMFS_GARBAGE_COLLECTION=true
    client_options: []
  - repository: singularity.galaxyproject.org
    stratum0: cvmfs0-psu0.galaxyproject.org
    owner: singularity
    server_options:
      - CVMFS_AUTO_TAG=false
      - CVMFS_GARBAGE_COLLECTION=true
      - CVMFS_AUTO_GC=false
    client_options: []
  - repository: usegalaxy.galaxyproject.org
    stratum0: cvmfs0-psu0.galaxyproject.org
    owner: usegalaxy
    server_options:
      - CVMFS_AUTO_TAG=false
      - CVMFS_GARBAGE_COLLECTION=true
      - CVMFS_AUTO_GC=false
    client_options: []
  - repository: cvmfs-config.galaxyproject.org
    stratum0: cvmfs0-psu0.galaxyproject.org
    owner: root
    server_options:
      - CVMFS_GARBAGE_COLLECTION=true
    client_options: []

cvmfs_keys:
  - path: /etc/cvmfs/keys/data.galaxyproject.org.pub
    owner: g2test
    key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5LHQuKWzcX5iBbCGsXGt
      6CRi9+a9cKZG4UlX/lJukEJ+3dSxVDWJs88PSdLk+E25494oU56hB8YeVq+W8AQE
      3LWx2K2ruRjEAI2o8sRgs/IbafjZ7cBuERzqj3Tn5qUIBFoKUMWMSIiWTQe2Sfnj
      GzfDoswr5TTk7aH/FIXUjLnLGGCOzPtUC244IhHARzu86bWYxQJUw0/kZl5wVGcH
      maSgr39h1xPst0Vx1keJ95AH0wqxPbCcyBGtF1L6HQlLidmoIDqcCQpLsGJJEoOs
      NVNhhcb66OJHah5ppI1N3cZehdaKyr1XcF9eedwLFTvuiwTn6qMmttT/tHX7rcxT
      owIDAQAB
      -----END PUBLIC KEY-----
  - path: /etc/cvmfs/keys/data.galaxyproject.org.crt
    owner: g2test
    key: |
      -----BEGIN CERTIFICATE-----
      MIIC9DCCAdwCCQDHxOGBpJCTaTANBgkqhkiG9w0BAQsFADA8MTowOAYDVQQDDDFk
      YXRhLmdhbGF4eXByb2plY3Qub3JnIENlcm5WTS1GUyBSZWxlYXNlIE1hbmFnZXJz
      MB4XDTE2MDMzMTE3MTA1MloXDTE3MDMzMTE3MTA1MlowPDE6MDgGA1UEAwwxZGF0
      YS5nYWxheHlwcm9qZWN0Lm9yZyBDZXJuVk0tRlMgUmVsZWFzZSBNYW5hZ2VyczCC
      ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANSqVuz/IGAeN5FtRezgmMQH
      MZR7Pu8BadU1yAPIAdkvg357xnF30UdzFFsx5UoIoaOTh07cFBpDZ/yD7evfbWFe
      u2HrI0N6gnSGJDal6jaRzB2gslRcE4d5B2U30xg0bXqVq2ASACCA6Tr4h909w5Hs
      qIT8mDN1kwg4yAC1CJ7lVEyd2omI/8FlJ+kONHOcKhuQzo/F4zSADYDk5bkJUFO2
      b51YcumqefJ12dP5L7w2wqbVRzo2MxtZWDrVuxAGEr+DU8BX9MXrQwxOXHADmWFD
      nCqlg0CoFR6CS2TzNcJdu0JmC/u+bgFeKkfekHiLg2RwhSYp0BLrxxUODXT7AHcC
      AwEAATANBgkqhkiG9w0BAQsFAAOCAQEAW0lijt9nXWIFX+ZiS6GqowD0XNzoWwwa
      05YHhivKlFzadBpsO9W5/Evq5Upi6plLQw0m2gYl6zaZKxXB5N90nvKqSL8tp4AZ
      C+qJdwBSJjG+rWZLh71AgTAfbKFxQUQea4s1yq6Y/iM/KpQj3xvGWCTtPHNVFqgX
      yc7Z5XE9YQIVsKO1Z4A1SVyp/F+xn9ikRfE1USuVXd14icPgSkLd4uCF1is9Ns2h
      IVsc8y8pyu4e2uiuvAiDkIWDwTj5LwvQlzCeAn4Z2crBEMDXOg5Ax7DE+8K+VaS7
      umt/c7usl22IscRFArkCPbTMJuUxyJYH8g9rl1AiziVw9zC9SCbD2w==
      -----END CERTIFICATE-----
  - path: /etc/cvmfs/keys/sandbox.galaxyproject.org.pub
    owner: sandbox
    key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1jHnrwsxMUkMZDAj9GMt
      WNCFFrNVejTTbyklk+52yyXgVgRWo1qN+5lh6W2UL/b2v9pOEzRVPZBQvNNwKo6P
      e+5p2JBVJ5yv7tpegEnHaRYw6yoHlWLzeSfiu8/yNp2s3jzK52zdLE9rZu7KlXH3
      EiY2LbU8wa0oah8BlvqWoHlWm78IQbbgK3Q0KmsXpvpjjhYkRWh/TL7KRmwT0b+C
      WDNbviUi62sBl1SWQ95kcsfqfviU94DKGWRWDYngnYRV5PZVLuUw8Egix6lW2Sj0
      l5LILRbaIyXiTsFqXfK1dtjAOmZMkX4wuBch13y9FhMCIRvBDWYQuyxugSC101Ur
      YwIDAQAB
      -----END PUBLIC KEY-----
  - path: /etc/cvmfs/keys/sandbox.galaxyproject.org.crt
    owner: sandbox
    key: |
      -----BEGIN CERTIFICATE-----
      MIIC+jCCAeICCQCM+ld6uTJAGjANBgkqhkiG9w0BAQsFADA/MT0wOwYDVQQDDDRz
      YW5kYm94LmdhbGF4eXByb2plY3Qub3JnIENlcm5WTS1GUyBSZWxlYXNlIE1hbmFn
      ZXJzMB4XDTE4MDUwODA3NDEwN1oXDTE5MDUwODA3NDEwN1owPzE9MDsGA1UEAww0
      c2FuZGJveC5nYWxheHlwcm9qZWN0Lm9yZyBDZXJuVk0tRlMgUmVsZWFzZSBNYW5h
      Z2VyczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOZ/1mSV1X2X5NPi
      B2b0v4Wep7+dwxLJR9ElKIx4ShzxY2fIT0XBjOGzBuaLRxOD52jA+mOFHa5Y2X65
      BawRQWCsewK6Qxk3ihYoQdXEd78ahydhOOsY9UDrpxLlsVtHokK2t2Zme5a6AmS8
      Rj4rwfBXErbCUiLK+BRSDWoIy2wvK3lErmFoXlr4cr7Yji9rAySytKWiTd49lneA
      05v/KFy8iuef2Y3g33atPUnZMw4l6IHkuCj3YSaLjwmWIC4X7cuG9R7SMSm4HMoY
      FKAVrDr+MxsGPIYZOWIbKlAcRXZHr2toOk/jZXBaezRP13W0zXL88ojdRXVv/U8L
      UW4fmMUCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAlzl6mshHyJ3H47RMDATRQkNN
      qDpIwaWftygAIJdnZWtiS0gut/NyN4l2lOz5mZ8cFzg2Y9JUGW+dtIwSW0QUvO4k
      q5+0qWTeD9dixj/ERIpMOake/Z2Gzzro3gHe+P3NHZ0slsnKzVDIZFZo6x/Lc701
      KENOt0oSF8kZTSxQoi0o0OBs5H3bA+afkNHxiXRwGG0nJ3sP2/MVrqrclYbLbRtA
      uFjvHWE2X2fDmvvmxaKEdTq5Ip0TK41f0H2cyTROn0ofRjx3wp8KjX0D2JJqZIau
      s6bKTTm3lyDf0+etkpE8J3TPbbSB/Ut+PCl8Efbzup1hmFpGZz/B89L9xi7+/w==
      -----END CERTIFICATE-----
  - path: /etc/cvmfs/keys/singularity.galaxyproject.org.pub
    owner: singularity
    key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt977djqKnD4WbYNq8VtU
      v9b8BgFzo1wh8rEUdj/2W9IvLXr5iWRrk1OvyZugYGxUg2JSVxiSXJhP1m8uBfBG
      aX2jn4iAq1suuIxJ6UMO+SYR/9yUANY/JKvfI9qHN9ItXxYveRXwORWb6s3zyCm3
      FFTRTUVQ5NFC+yT13BeIKyLMhT8yMSnlZ/5f8kuwSC1v/2QcC6UWDrHaUcEGWcHS
      EfiTov/pVXq0Hv3M2kwBWMqWeFey4WbnuNOCXYrYy9VCxmPAtO0TjFuThMr9XyWc
      Zu859ZLVjmkMxPxEPNxgNnc+DohK5wFPt7MHSejvCmd1J8iL4DOXUN2VvgJ9NrUN
      hwIDAQAB
      -----END PUBLIC KEY-----
  - path: /etc/cvmfs/keys/singularity.galaxyproject.org.crt
    owner: singularity
    key: |
      -----BEGIN CERTIFICATE-----
      MIIDAjCCAeoCCQD7gQ6vXswQHDANBgkqhkiG9w0BAQsFADBDMUEwPwYDVQQDDDhz
      aW5ndWxhcml0eS5nYWxheHlwcm9qZWN0Lm9yZyBDZXJuVk0tRlMgUmVsZWFzZSBN
      YW5hZ2VyczAeFw0xODA1MTAxMjEyMzdaFw0xOTA1MTAxMjEyMzdaMEMxQTA/BgNV
      BAMMOHNpbmd1bGFyaXR5LmdhbGF4eXByb2plY3Qub3JnIENlcm5WTS1GUyBSZWxl
      YXNlIE1hbmFnZXJzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7mlC
      I6xxdekF0JTGi/wzBh5TVsm7JRZWZ7fRr7zE+WyxOGAD1qKckchqN168xd4a/7Rb
      BRt5jGozziuPk86CjfP2C0B/KxPdNuD/ffBKPVBbEqkmMgv0YN2ycFLVIkg0HkAa
      TGidRljIpGqQRFdjCNXNHnkax+mCU1+wxR9GfNR0HVO7G4PK57b279oZPotIn4h4
      yBfhJrNZG2v9fdVfXT1188Pc98IUhrWjZQc/HjTRn+1i/NO8TJ8P76hC0nGlg4Ks
      JxM42Onf2a9EeuJCdwgbwh7zzUdthCCOtOf0GCHchkhUXgO8qk3AKgYBGEJFexEE
      ogJzRE8D+24seye8MQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQAC1yKa2CHQnmmC
      K5UXqYYN3eSWXB1KNiBzpKVDNvqqe6oVXKW4eDXZOmoSf5xeVxL5424fqp+ZHEH0
      HoL4e1/GofbYtw382zEeeT4LHgDQ3gsAX18hQJK0k4M5YHIDDWHBpLBvBrzv4kyQ
      i3u7qvXAUBb40eINU/4LdCsHMhxBwUS1hymc/ugG77uUTcw2UlkuRlTgqleFYeqE
      ehwMznbk6ldXB03sf9+idJKzegHD8Hgol1odof/3IGt3hBBIRY8wdQJ7Fd65Svf7
      br7UXF4V9HUbq5OYwhKVS58wtSMcn4nAmhuiA9qna9Yf6k8XzJYeVP1Z4vCal6L1
      BDIF5yII
      -----END CERTIFICATE-----
  - path: /etc/cvmfs/keys/usegalaxy.galaxyproject.org.pub
    owner: usegalaxy
    key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsqb8HIG5T/juOmVpByIE
      UfboKj7S2LbnWCZdCAoA9EfQfsxi/p3iWu1j9/0iJjf4yKs+pI6mJL/t+txB9fM5
      EYdYJv/awH7W4A47e8/CR25HzoM9PjxbssRbHSGWLrDBPHUcyQh7gZGqJYdXIyeS
      DrgPoftn04xuLQvmPWbi8Ng14c+Kn8947PxZ5hVOmApEd4gzkHI0qFfC7dTN/rTh
      KdC5mWONdRmmSDM4OmgJl7wdzE5pUTA+H1GagESxG4Cm/7EN9ZnVgWdb/sgVTxHG
      e3odhIy/hV82RHkaW456/jhd8tD8LHpY8jdM/rWvwrBgI7WntqSijOUe2a6uC7S1
      sQIDAQAB
      -----END PUBLIC KEY-----
  - path: /etc/cvmfs/keys/usegalaxy.galaxyproject.org.crt
    owner: usegalaxy
    key: |
      -----BEGIN CERTIFICATE-----
      MIIC/jCCAeYCCQDxcxeNf3KBwTANBgkqhkiG9w0BAQsFADBBMT8wPQYDVQQDDDZ1
      c2VnYWxheHkuZ2FsYXh5cHJvamVjdC5vcmcgQ2VyblZNLUZTIFJlbGVhc2UgTWFu
      YWdlcnMwHhcNMTkwNjE5MTkwOTAxWhcNMjAwNjE4MTkwOTAxWjBBMT8wPQYDVQQD
      DDZ1c2VnYWxheHkuZ2FsYXh5cHJvamVjdC5vcmcgQ2VyblZNLUZTIFJlbGVhc2Ug
      TWFuYWdlcnMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDVnlqvCHcD
      s65dMgYcXUVZ5bLyDh8/mfnyu+jiYQiuWMV4aDD9rXy8elgeTY2sRO/S6IaFPQk9
      PUpgGnzm7GahICXmWSZP98iUIpyBJ0NZSAsUOJcr8/e1YZ4TcRabv2CL/s1JjM0G
      OBvPf5yPvDRc/ntz2HhAMCtBhoMlpQL6IsWC1Kj45F9oQOQonB0iiNo/03egaODB
      l6mKWR0r+xdXJo9yr5+eEXb7GbSEdLLNVWYcEtBXwJXfYlsC8SMdg1pwvDOtjspF
      nGc2FrbmvZA9L7KampgnUUs1Urif6kL2YdtX4RH3VROyyuBaNaxdLAWqo6qSUmzY
      +8HXBsOPKnzxAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAEFFAtvQkKu/5U3wlovs
      sOd/6pshb3iVfWCSP+LBFboPfL1DoX+ZgHkcAQMpiF47ZBOnj7JjTRFdo1xkM9eo
      u+gJ9NKo4Nzz0cwgwV87ISsRKonWdqfy0j5yvDHQxrM2AB5a+pqhrJCXYE+PA+it
      Hta5dv+907i8U5vrHhdMdsyPueMWAQ1g11TohFIg7LrAW/sexmdfm1lTihJCwkL5
      4PW7mlpIdOXnK3eZL3dQU7v+VVK/nUEdlip3ttPxAIzrk/E6TqN2mI/EFyXDPHy2
      48y43fE7u83CX6XXXHhbhcrR4LOmKMUfD3jE6Sv9WUhDPrHEaNChZ4Z8BEs1Mvrh
      ZY4=
      -----END CERTIFICATE-----
  - path: /etc/cvmfs/keys/cvmfs-config.galaxyproject.org.pub
    owner: root
    key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuJZTWTY3/dBfspFKifv8
      TWuuT2Zzoo1cAskKpKu5gsUAyDFbZfYBEy91qbLPC3TuUm2zdPNsjCQbbq1Liufk
      uNPZJ8Ubn5PR6kndwrdD13NVHZpXVml1+ooTSF5CL3x/KUkYiyRz94sAr9trVoSx
      THW2buV7ADUYivX7ofCvBu5T6YngbPZNIxDB4mh7cEal/UDtxV683A/5RL4wIYvt
      S5SVemmu6Yb8GkGwLGmMVLYXutuaHdMFyKzWm+qFlG5JRz4okUWERvtJ2QAJPOzL
      mAG1ceyBFowj/r3iJTa+Jcif2uAmZxg+cHkZG5KzATykF82UH1ojUzREMMDcPJi2
      dQIDAQAB
      -----END PUBLIC KEY-----
  - path: /etc/cvmfs/keys/cvmfs-config.galaxyproject.org.crt
    owner: root
    key: |
      -----BEGIN CERTIFICATE-----
      MIIDBDCCAewCCQDY/xeqeOP2rTANBgkqhkiG9w0BAQsFADBEMUIwQAYDVQQDDDlj
      dm1mcy1jb25maWcuZ2FsYXh5cHJvamVjdC5vcmcgQ2VyblZNLUZTIFJlbGVhc2Ug
      TWFuYWdlcnMwHhcNMTkwNjE5MTkyMTUzWhcNMjAwNjE4MTkyMTUzWjBEMUIwQAYD
      VQQDDDljdm1mcy1jb25maWcuZ2FsYXh5cHJvamVjdC5vcmcgQ2VyblZNLUZTIFJl
      bGVhc2UgTWFuYWdlcnMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQD+
      EamXuc5K7l+cCQOCdvmXQ9TeEI+BBpHWg0i6gMLbSm0+QM6fnIU9KOrlQ78I733H
      HG+nqRuRubYUK3zudhK6XjCTUU93FosxwFAcEzhaD6tb9UXxMcXwVVIr2r4wtAKB
      QlA5InAjMS8de0log8aukVVpQC4CtZxj8RjV1TH9cpUK6F/kjF+Ouwln6+7lS7aB
      ENqugCdd7BeN2iOgVayVMycOoK4tbX9wJYXR2sqsq5+Bq8TfgpVvDOwzREAdfI/m
      wy+Avvc5xYIjLdBon8RpiePVHMXK8ejyxxKtv5wbmw40JwpBlXXRsCbNrM3uKC8I
      xOu3J+YjDZqFJjLKFIoXAgMBAAEwDQYJKoZIhvcNAQELBQADggEBANc+E7lbrgqO
      q/R/yVwEQ2LQf2wyfZupAB+zrOD1+P9PKcIj9HukE+q71SrhNhGoDFqm8Ne6dNXz
      8KzBDQzjtt6OIs0j4jwSmP2W7Z6yjOOcFP7JKGLjT7ob/Hq1qpgjchOVe4lv9neA
      h7HXivfJdHSEqsQJnjaJu6rhT/qoDs1gF1S+Sy23saSQ8VpVbe4pFBf/FB3jFpHI
      z+Nbpt1pMOjAvZoEGEQS1q6LYDMr8aMp+bL8C+A07ykn5jGOp29aXEtB1sW0jY5s
      K77KJfKqQGEbNkmbLcabisqGtG+RAyrwe1LUaJTtlx2Qba1sjMDd3Fgb09sZZ2Er
      4UHY3TOaxvs=
      -----END CERTIFICATE-----

host_users:
  - name: g2test
    uid: 819456
    group: G-803372
    comment: "Galaxy Test"
    home: /home/g2test
    shell: /bin/bash
  - name: g2main
    uid: 819800
    group: G-803372
    comment: "Galaxy Main"
    home: /home/g2main
    shell: /bin/bash
  - name: sandbox
    comment: "CVMFS Sandbox"
    home: /home/sandbox
    shell: /bin/bash
    system: true
    #groups: docker
  - name: singularity
    comment: "Singularity Images"
    home: /home/singularity
    shell: /bin/bash
    system: yes
  - name: usegalaxy
    comment: "UseGalaxy Common Data"
    home: /home/usegalaxy
    shell: /bin/bash
    system: yes

host_groups:
  - name: G-803372
    gid: 803372
