$ANSIBLE_VAULT;1.1;AES256
36613262316635613039633865656530636166663230626262616661636363376338373033633737
3730623231323333323235616433666130323862663765300a643434323566333239613563313766
32383836353063396262326565653832633466316230356437353762623338666430396363356336
3665633536613632350a346232316334346630323437383135396161376630653064623363653834
65616433356563633330623561366263306136663566363264623064333538386162343030373265
62333736626466633432643138303837336662633731366466613465386165393866633362323637
30373965613165663536303039646139336433666663386431386564323038616138306136636635
31323631646161663437326331663061376333363362613561623837353661383830663330643136
62363062363430646164626634646262353531373036373731313939386437663163316364383032
30366461376665303962333062346531323165323331613039396339646134623265396165623737
373339343962346234396262653662303430
