---

# 48 GB
cvmfs_quota_limit: 49152

jsgalaxynodes_group_groups:
  - name: G-803372
    gid: 803372
  - name: TACC-ACS
    gid: 814239

jsgalaxynodes_group_users:
  - name: g2test
    group: G-803372
    groups: TACC-ACS
    comment: 'Galaxy Test Server'
    uid: 819456
    home: /home/g2test
    shell: /bin/bash
  - name: g2main
    group: G-803372
    groups: TACC-ACS
    comment: 'Galaxy Main Server'
    uid: 819800
    home: /home/g2main
    shell: /bin/bash

# prevent overwrite by all.yml
mounts:
  - src: 129.114.51.136:/gpfs/corral3/repl/projects/galaxy
    path: /galaxy-repl
    fstype: nfs
    opts: rw,nosuid,noatime,rsize=1048576,wsize=1048576,intr,nfsvers=3,tcp,soft,addr=129.114.51.136
    #owner: ndc
    owner: 815276
    #group: G-803372
    group: 803372
