---

cvmfs_keys:
  - path: /etc/cvmfs/keys/test.galaxyproject.org.pub
    owner: g2test
    key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtfc5SSX9ALcrukWYcxkI
      mkLhlkJa5tCP1oZNWFA7GfE4xQW2vcKE5qmbZqhYVfdiy+FHPnhWPJp577hekD2F
      vMITbApdZ0265AjRC0+EKKxpMF8zZ0q71vCFxvdK0c3DtT/3LmqKrr2wimtJZjQN
      UAZcQG2ykzeHzFZ46w74IO0o8Fv/w2XEbYI0QqbNFv+0hcp5SruFqaaLsRZdd6Bn
      3iSylgVRQ5b+h1LfB/EuEpSmH1sDozZ4tU0fpbrBSknK76aad1o/cvWY1X87ToUV
      helU0HE2Rw/u9EqJDvPFTbUmad3MtspkqbG5Eo7lI+ktzbcD7UTsQ/7noIXIQ5dD
      PwIDAQAB
      -----END PUBLIC KEY-----
  - path: /etc/cvmfs/keys/test.galaxyproject.org.crt
    owner: g2test
    key: |
      -----BEGIN CERTIFICATE-----
      MIIC9DCCAdwCCQC3lM3Z8xqGAjANBgkqhkiG9w0BAQsFADA8MTowOAYDVQQDDDF0
      ZXN0LmdhbGF4eXByb2plY3Qub3JnIENlcm5WTS1GUyBSZWxlYXNlIE1hbmFnZXJz
      MB4XDTE2MDMzMDAzMjkyN1oXDTE3MDMzMDAzMjkyN1owPDE6MDgGA1UEAwwxdGVz
      dC5nYWxheHlwcm9qZWN0Lm9yZyBDZXJuVk0tRlMgUmVsZWFzZSBNYW5hZ2VyczCC
      ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALw45Jfo9SD2LX8fA3/fULz7
      QQakPXc+s61dKIB7eBG5ZRd99IFu3RJbinn2/zx9V8fgsMPvj2fYyHqRJ2jUXsre
      sIDLB8yEH97HLIUXwZFdA1RF+z1BTsH0PoUKeI/jQR2NqSEBBLOYQI3pFq+W7b32
      gDl+uAasx4pc0VE6p/3Hfre7Fki0vNodcC4eZr8nr0vfkx8dDFm+7fTzqMjBCcNP
      qp+vdqyH/D72qWzV5+Db0a2G5NhuPzd7/wjrSKH46L8BSgjIucx6YBYeXA5D1akR
      oj+F/mygUHXx2XeAknjDN03jspRgSJGwcDxfvV3H9KRMrOi6Glt2AsxW9B6TbnsC
      AwEAATANBgkqhkiG9w0BAQsFAAOCAQEAe4p3qRPHMGikobrcqZMfb2eOQCALMbxL
      g52xyd85uoXtM/4HZl1Y5oaUdalfJET0T2mI0Nxt88GXkI6jtNsKJGg2SKlNrhCP
      HzJRc0MZ+TvQFWWe23nY3krXKqWSXIT41AUMYz4t+BuJPb32y7cIFmX2SNPsaWFj
      aOFCh39K3wq6OD1SEp3wWPUQqC6dQEiQthG/xRe8HBZXxyGuGsGuZbC5L6ltUEvn
      QbKTk0xXXpBChXvEaSD1D5TATVUFbf8fwqHjkDVarhJxAtrv1p0k/EzJGrhbcEh+
      ka2GnWe8NST2zVvhBhnKVErSMJa0ZVSikljy8/ftJ24gfCjDFf6mEg==
      -----END CERTIFICATE-----
  - path: /etc/cvmfs/keys/data.galaxyproject.org.pub
    owner: g2test
    key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5LHQuKWzcX5iBbCGsXGt
      6CRi9+a9cKZG4UlX/lJukEJ+3dSxVDWJs88PSdLk+E25494oU56hB8YeVq+W8AQE
      3LWx2K2ruRjEAI2o8sRgs/IbafjZ7cBuERzqj3Tn5qUIBFoKUMWMSIiWTQe2Sfnj
      GzfDoswr5TTk7aH/FIXUjLnLGGCOzPtUC244IhHARzu86bWYxQJUw0/kZl5wVGcH
      maSgr39h1xPst0Vx1keJ95AH0wqxPbCcyBGtF1L6HQlLidmoIDqcCQpLsGJJEoOs
      NVNhhcb66OJHah5ppI1N3cZehdaKyr1XcF9eedwLFTvuiwTn6qMmttT/tHX7rcxT
      owIDAQAB
      -----END PUBLIC KEY-----
  - path: /etc/cvmfs/keys/data.galaxyproject.org.crt
    owner: g2test
    key: |
      -----BEGIN CERTIFICATE-----
      MIIC9DCCAdwCCQDHxOGBpJCTaTANBgkqhkiG9w0BAQsFADA8MTowOAYDVQQDDDFk
      YXRhLmdhbGF4eXByb2plY3Qub3JnIENlcm5WTS1GUyBSZWxlYXNlIE1hbmFnZXJz
      MB4XDTE2MDMzMTE3MTA1MloXDTE3MDMzMTE3MTA1MlowPDE6MDgGA1UEAwwxZGF0
      YS5nYWxheHlwcm9qZWN0Lm9yZyBDZXJuVk0tRlMgUmVsZWFzZSBNYW5hZ2VyczCC
      ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANSqVuz/IGAeN5FtRezgmMQH
      MZR7Pu8BadU1yAPIAdkvg357xnF30UdzFFsx5UoIoaOTh07cFBpDZ/yD7evfbWFe
      u2HrI0N6gnSGJDal6jaRzB2gslRcE4d5B2U30xg0bXqVq2ASACCA6Tr4h909w5Hs
      qIT8mDN1kwg4yAC1CJ7lVEyd2omI/8FlJ+kONHOcKhuQzo/F4zSADYDk5bkJUFO2
      b51YcumqefJ12dP5L7w2wqbVRzo2MxtZWDrVuxAGEr+DU8BX9MXrQwxOXHADmWFD
      nCqlg0CoFR6CS2TzNcJdu0JmC/u+bgFeKkfekHiLg2RwhSYp0BLrxxUODXT7AHcC
      AwEAATANBgkqhkiG9w0BAQsFAAOCAQEAW0lijt9nXWIFX+ZiS6GqowD0XNzoWwwa
      05YHhivKlFzadBpsO9W5/Evq5Upi6plLQw0m2gYl6zaZKxXB5N90nvKqSL8tp4AZ
      C+qJdwBSJjG+rWZLh71AgTAfbKFxQUQea4s1yq6Y/iM/KpQj3xvGWCTtPHNVFqgX
      yc7Z5XE9YQIVsKO1Z4A1SVyp/F+xn9ikRfE1USuVXd14icPgSkLd4uCF1is9Ns2h
      IVsc8y8pyu4e2uiuvAiDkIWDwTj5LwvQlzCeAn4Z2crBEMDXOg5Ax7DE+8K+VaS7
      umt/c7usl22IscRFArkCPbTMJuUxyJYH8g9rl1AiziVw9zC9SCbD2w==
      -----END CERTIFICATE-----
  - path: /etc/cvmfs/keys/main.galaxyproject.org.pub
    owner: g2main
    key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6S6Tugcv4kk4C06f574l
      YCXQdK6lv2m7mqCh60G0zL1+rAkkEBDWna0yMQLBbj+yDsHjcOe0yISzbTfzG6wk
      KnHZUQ/JOeK7lUAbDMxHqnjkEPAbAl4vXl2Y04MW2lzJtXcDKakmLirvV/dfUYqE
      gGGx0dc/Z+XmUTf1DvZFJknrBUUxO5+F6m7k/NGrlpAca+e9B0kwCclaE4NyaNWK
      Jv5rPWCYz5/sDNW4cNvBdBjwGf46etbczmJoTAbl0oM6LLGdebwkJStd0R1wkj+A
      torRYcoFZICTZqY9e/KsadHUeZnH3RvfMypH5oS1POzsFszoSxBhZIBkZbG3/f9Y
      OQIDAQAB
      -----END PUBLIC KEY-----
  - path: /etc/cvmfs/keys/main.galaxyproject.org.crt
    owner: g2main
    key: |
      -----BEGIN CERTIFICATE-----
      MIIC9DCCAdwCCQCu1/uoOM2BxjANBgkqhkiG9w0BAQsFADA8MTowOAYDVQQDDDFt
      YWluLmdhbGF4eXByb2plY3Qub3JnIENlcm5WTS1GUyBSZWxlYXNlIE1hbmFnZXJz
      MB4XDTE2MDQxMTE1MjkxN1oXDTE3MDQxMTE1MjkxN1owPDE6MDgGA1UEAwwxbWFp
      bi5nYWxheHlwcm9qZWN0Lm9yZyBDZXJuVk0tRlMgUmVsZWFzZSBNYW5hZ2VyczCC
      ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALsxdKt+ol4QOGsIy3Z49m7s
      uvfjFVwCXVBJcZMR1iaqIdqpVMn/9h4MQZn6npxwYFZ5zFirVs409kIDbUUNnF9V
      eD16AEhgHuarXsoiFG7msy6YhXa2ErIoR378b7sF5fSBzcYlcgUJb2DzS3vr17H6
      ZMxj0IMymdrynBaoUi5GyD7471cWr09onL8LSrO1gxXYVBl4RkLKIEOaRs8Kgf1g
      trZE2rfJXqseQHUfGUGQH4jP++nNPSBNxQGyHMZxAPJe5OukcHpsp+QvtSJKNTkC
      A4G1AEEbxw8bi3sER6tpzZEg3HuI8v03jOf5b/3bdHTAz3Au9jxO/h9sPqqszxsC
      AwEAATANBgkqhkiG9w0BAQsFAAOCAQEAgJoWcG45RwS6VlkT7CDFyb1eVvt/i3aJ
      XXPod2odg49zKBZ2pidKYkKSgmMfF6BKS3VIWW6Op5kZrw1gNSU22xMwqTHgkvOl
      c13DZGZbsDlYL2hp7fFg3pLw2KFITY5B31PCOqrXXpgPQPL/uedV2bjGHcIeerPj
      9GbQbSqSRNZ4Kq8mz4zjMPUC01nJL+S82Dz04JjIVqhT/bmMn67AeFqxBzN3B1wk
      bAGzbVAm14suDOEoallf/MXSRkeU6J3hEGdWbAS/0HfyTpPzdlytyihvz5R0UDZp
      3LfKBSCPAcZI4A1CecNIBgCvV3YT4qow68xovCmI9x7YXbdXwAA3Zw==
      -----END CERTIFICATE-----
  - path: /etc/cvmfs/keys/sandbox.galaxyproject.org.pub
    owner: root
    key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1jHnrwsxMUkMZDAj9GMt
      WNCFFrNVejTTbyklk+52yyXgVgRWo1qN+5lh6W2UL/b2v9pOEzRVPZBQvNNwKo6P
      e+5p2JBVJ5yv7tpegEnHaRYw6yoHlWLzeSfiu8/yNp2s3jzK52zdLE9rZu7KlXH3
      EiY2LbU8wa0oah8BlvqWoHlWm78IQbbgK3Q0KmsXpvpjjhYkRWh/TL7KRmwT0b+C
      WDNbviUi62sBl1SWQ95kcsfqfviU94DKGWRWDYngnYRV5PZVLuUw8Egix6lW2Sj0
      l5LILRbaIyXiTsFqXfK1dtjAOmZMkX4wuBch13y9FhMCIRvBDWYQuyxugSC101Ur
      YwIDAQAB
      -----END PUBLIC KEY-----
  - path: /etc/cvmfs/keys/sandbox.galaxyproject.org.crt
    owner: root
    key: |
      -----BEGIN CERTIFICATE-----
      MIIC+jCCAeICCQCM+ld6uTJAGjANBgkqhkiG9w0BAQsFADA/MT0wOwYDVQQDDDRz
      YW5kYm94LmdhbGF4eXByb2plY3Qub3JnIENlcm5WTS1GUyBSZWxlYXNlIE1hbmFn
      ZXJzMB4XDTE4MDUwODA3NDEwN1oXDTE5MDUwODA3NDEwN1owPzE9MDsGA1UEAww0
      c2FuZGJveC5nYWxheHlwcm9qZWN0Lm9yZyBDZXJuVk0tRlMgUmVsZWFzZSBNYW5h
      Z2VyczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOZ/1mSV1X2X5NPi
      B2b0v4Wep7+dwxLJR9ElKIx4ShzxY2fIT0XBjOGzBuaLRxOD52jA+mOFHa5Y2X65
      BawRQWCsewK6Qxk3ihYoQdXEd78ahydhOOsY9UDrpxLlsVtHokK2t2Zme5a6AmS8
      Rj4rwfBXErbCUiLK+BRSDWoIy2wvK3lErmFoXlr4cr7Yji9rAySytKWiTd49lneA
      05v/KFy8iuef2Y3g33atPUnZMw4l6IHkuCj3YSaLjwmWIC4X7cuG9R7SMSm4HMoY
      FKAVrDr+MxsGPIYZOWIbKlAcRXZHr2toOk/jZXBaezRP13W0zXL88ojdRXVv/U8L
      UW4fmMUCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAlzl6mshHyJ3H47RMDATRQkNN
      qDpIwaWftygAIJdnZWtiS0gut/NyN4l2lOz5mZ8cFzg2Y9JUGW+dtIwSW0QUvO4k
      q5+0qWTeD9dixj/ERIpMOake/Z2Gzzro3gHe+P3NHZ0slsnKzVDIZFZo6x/Lc701
      KENOt0oSF8kZTSxQoi0o0OBs5H3bA+afkNHxiXRwGG0nJ3sP2/MVrqrclYbLbRtA
      uFjvHWE2X2fDmvvmxaKEdTq5Ip0TK41f0H2cyTROn0ofRjx3wp8KjX0D2JJqZIau
      s6bKTTm3lyDf0+etkpE8J3TPbbSB/Ut+PCl8Efbzup1hmFpGZz/B89L9xi7+/w==
      -----END CERTIFICATE-----
  - path: /etc/cvmfs/keys/singularity.galaxyproject.org.pub
    owner: root
    key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt977djqKnD4WbYNq8VtU
      v9b8BgFzo1wh8rEUdj/2W9IvLXr5iWRrk1OvyZugYGxUg2JSVxiSXJhP1m8uBfBG
      aX2jn4iAq1suuIxJ6UMO+SYR/9yUANY/JKvfI9qHN9ItXxYveRXwORWb6s3zyCm3
      FFTRTUVQ5NFC+yT13BeIKyLMhT8yMSnlZ/5f8kuwSC1v/2QcC6UWDrHaUcEGWcHS
      EfiTov/pVXq0Hv3M2kwBWMqWeFey4WbnuNOCXYrYy9VCxmPAtO0TjFuThMr9XyWc
      Zu859ZLVjmkMxPxEPNxgNnc+DohK5wFPt7MHSejvCmd1J8iL4DOXUN2VvgJ9NrUN
      hwIDAQAB
      -----END PUBLIC KEY-----
  - path: /etc/cvmfs/keys/singularity.galaxyproject.org.crt
    owner: root
    key: |
      -----BEGIN CERTIFICATE-----
      MIIDAjCCAeoCCQD7gQ6vXswQHDANBgkqhkiG9w0BAQsFADBDMUEwPwYDVQQDDDhz
      aW5ndWxhcml0eS5nYWxheHlwcm9qZWN0Lm9yZyBDZXJuVk0tRlMgUmVsZWFzZSBN
      YW5hZ2VyczAeFw0xODA1MTAxMjEyMzdaFw0xOTA1MTAxMjEyMzdaMEMxQTA/BgNV
      BAMMOHNpbmd1bGFyaXR5LmdhbGF4eXByb2plY3Qub3JnIENlcm5WTS1GUyBSZWxl
      YXNlIE1hbmFnZXJzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7mlC
      I6xxdekF0JTGi/wzBh5TVsm7JRZWZ7fRr7zE+WyxOGAD1qKckchqN168xd4a/7Rb
      BRt5jGozziuPk86CjfP2C0B/KxPdNuD/ffBKPVBbEqkmMgv0YN2ycFLVIkg0HkAa
      TGidRljIpGqQRFdjCNXNHnkax+mCU1+wxR9GfNR0HVO7G4PK57b279oZPotIn4h4
      yBfhJrNZG2v9fdVfXT1188Pc98IUhrWjZQc/HjTRn+1i/NO8TJ8P76hC0nGlg4Ks
      JxM42Onf2a9EeuJCdwgbwh7zzUdthCCOtOf0GCHchkhUXgO8qk3AKgYBGEJFexEE
      ogJzRE8D+24seye8MQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQAC1yKa2CHQnmmC
      K5UXqYYN3eSWXB1KNiBzpKVDNvqqe6oVXKW4eDXZOmoSf5xeVxL5424fqp+ZHEH0
      HoL4e1/GofbYtw382zEeeT4LHgDQ3gsAX18hQJK0k4M5YHIDDWHBpLBvBrzv4kyQ
      i3u7qvXAUBb40eINU/4LdCsHMhxBwUS1hymc/ugG77uUTcw2UlkuRlTgqleFYeqE
      ehwMznbk6ldXB03sf9+idJKzegHD8Hgol1odof/3IGt3hBBIRY8wdQJ7Fd65Svf7
      br7UXF4V9HUbq5OYwhKVS58wtSMcn4nAmhuiA9qna9Yf6k8XzJYeVP1Z4vCal6L1
      BDIF5yII
      -----END CERTIFICATE-----

cvmfs_private_keys: []

cvmfs_server_urls:
  - domain: galaxyproject.org
    urls:
      - "http://cvmfs1-tacc0.galaxyproject.org/cvmfs/@fqrn@"
      - "http://cvmfs1-iu0.galaxyproject.org/cvmfs/@fqrn@"
      - "http://cvmfs1-psu0.galaxyproject.org/cvmfs/@fqrn@"

cvmfs_repositories:
  - repository: test.galaxyproject.org
    stratum0: cvmfs0-tacc0.galaxyproject.org
    owner: g2test
    server_options:
      - CVMFS_AUTO_GC=false
    client_options: []
  - repository: main.galaxyproject.org
    stratum0: cvmfs0-tacc0.galaxyproject.org
    owner: g2main
    server_options:
      - CVMFS_AUTO_GC=false
    client_options: []
  - repository: data.galaxyproject.org
    stratum0: cvmfs0-psu0.galaxyproject.org
    owner: g2test
    server_options:
      - CVMFS_AUTO_GC=false
    client_options: []
  - repository: sandbox.galaxyproject.org
    stratum0: cvmfs0-psu0.galaxyproject.org
    owner: sandbox
    server_options: []
    client_options: []
  - repository: singularity.galaxyproject.org
    stratum0: cvmfs0-psu0.galaxyproject.org
    owner: singularity
    server_options: []
    client_options: []


cvmfs_http_proxies:
  - DIRECT

cvmfs_stratum1_servers:
  - "cvmfs1-tacc0.galaxyproject.org"
  - "cvmfs1-iu0.galaxyproject.org"
  - "cvmfs1-psu0.galaxyproject.org"

cvmfs_stratum1_apache_port: 8008
# in MB
cvmfs_stratum1_cache_mem: 128

# Whether the client or server should be upgraded or just installed if missing
cvmfs_upgrade_client: false
cvmfs_upgrade_server: false

# Install a setuid binary allowing unprivileged users to call `cvmfs_config wipecache` or `cvmfs_talk remount sync`?
cvmfs_install_setuid_cvmfs_wipecache: no
cvmfs_install_setuid_cvmfs_remount_sync: no
